/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UQRv2;

import java.io.*;
import java.util.*;
import okhttp3.*;

public class App {

    public static void main(String[] args) {

        if (args.length == 2) {
            try {
                String filePath = args[0];
                String apiKey = args[1];
                System.out.println("Sending this file to UQRv2 ... "+ filePath);
                OkHttpClient client = new OkHttpClient().newBuilder()
                    .build();
                MediaType mediaType = MediaType.parse("text/plain");
                RequestBody body = new MultipartBody.Builder().setType(MultipartBody.FORM)
                    .addFormDataPart("file","Macao-vaccine-cert.png",
                    RequestBody.create(MediaType.parse("application/octet-stream"),
                    new File(filePath)))
                    .build();
                Request request = new Request.Builder()
                    .url("https://universal-qr-reader-v2-singapore-cc-stg.stg.travel.affinidi.com/api/v1/read-file")
                    .method("POST", body)
                    .addHeader("Api-Key", apiKey)
                    .build();
                Response response = client.newCall(request).execute();
                System.out.println(response.body().string());
            } catch (IOException ioe) {

            }
        } 

        
        
    }
}
